NXP-21725: make LongProperty wrap any NumberFormatException
nuxeo/nuxeo pull request #4356
Opened 2020-10-02 16:50 UTC by troger

2020-10-02 16:50 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-21725](https://jira.nuxeo.com/browse/NXP-21725): Decimal values in EXIF metadata raise a NumberFormatException

2020-10-05 08:19 UTC, kevinleturc commented on modules/platform/nuxeo-binary-metadata/src/main/java/org/nuxeo/binary/metadata/internals/BinaryMetadataServiceImpl.java
>  import org.apache.commons.logging.LogFactory;
These ones should be cleared because unused.

2020-10-05 09:32 UTC, kevinleturc submitted a review, later dismissed

2020-10-05 14:02 UTC, efge requested changes
I feel like this fix is incomplete if we don't do similar changes to `DoubleProperty`...

2020-10-06 08:16 UTC, kevinleturc approved these changes

2020-10-06 08:20 UTC, kevinleturc approved these changes

2020-10-06 11:28 UTC, efge approved these changes

2020-10-19 08:33 UTC, merged