NXP-29700: fix blob extraction for list of complex property
nuxeo/nuxeo pull request #4392
Opened 2020-10-16 16:27 UTC by troger

2020-10-16 16:27 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29700](https://jira.nuxeo.com/browse/NXP-29700): Fix NPE in BlobsExtractor#findBlobsProperties

2020-10-19 08:13 UTC, bdelbosc submitted a review, later dismissed

2020-10-19 08:31 UTC, troger commented
More cleanup & improve test with multiple blobs.

2020-10-19 09:57 UTC, bdelbosc submitted a review, later dismissed

2020-10-19 13:12 UTC, efge requested changes

2020-10-19 13:12 UTC, efge commented on modules/core/nuxeo-core-api/src/main/java/org/nuxeo/ecm/core/utils/BlobsExtractor.java
>                  List<String> subPath = split.subList(1, split.size());
`split.get(0)` and `List<String> subPath` could be factored out of the `if` and loop.

2020-10-19 13:38 UTC, efge approved these changes

2020-10-19 14:02 UTC, kevinleturc submitted a review, later dismissed

2020-10-22 16:50 UTC, efge approved these changes

2020-10-23 08:39 UTC, kevinleturc approved these changes

2020-10-23 08:41 UTC, merged