Feature NXP-29836 gcp chunk upload
nuxeo/nuxeo pull request #4492
Opened 2020-11-24 12:23 UTC by kevinleturc

2020-11-24 12:23 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29836](https://jira.nuxeo.com/browse/NXP-29836): Implement retry with exponential backoff in GCP connector

2020-11-24 12:39 UTC, efge requested changes

2020-11-24 12:39 UTC, efge commented on modules/core/nuxeo-core-binarymanager-cloud/nuxeo-core-binarymanager-gcp/src/main/java/org/nuxeo/ecm/core/storage/gcp/GoogleStorageBinaryManager.java
> +    public static final int DEFAULT_UPLOAD_CHUNK_SIZE = 2048 * 1024; // 2 Mo
`Mo` -> `MB`

2020-11-24 12:39 UTC, efge commented on modules/core/nuxeo-core-binarymanager-cloud/nuxeo-core-binarymanager-gcp/src/main/java/org/nuxeo/ecm/core/storage/gcp/GoogleStorageBinaryManager.java
> +                int bufferLength;
`bufferLength` definition can be moved inside the `try`.
Probably `buffer` too.

2020-11-24 13:17 UTC, efge approved these changes

2020-11-25 07:05 UTC, ataillefer approved these changes

2020-11-25 11:59 UTC, merged