NXP-29798: Implement get server info endpoint
nuxeo/nuxeo pull request #4501
Opened 2020-12-01 15:37 UTC by kevinleturc

2020-12-01 15:38 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29798](https://jira.nuxeo.com/browse/NXP-29798): Server Version Information Endpoint

2020-12-01 15:44 UTC, efge commented on modules/platform/nuxeo-admin-center/nuxeo-admin-center-core/src/main/java/org/nuxeo/ecm/admin/runtime/ServerInfo.java
> +    public String getClusterNodeId() {
`isClusterEnabled` would be useful too I think

2020-12-04 16:12 UTC, efge requested changes

2020-12-04 16:12 UTC, efge commented on modules/platform/rest-api/nuxeo-rest-api-test/src/test/java/org/nuxeo/ecm/restapi/server/jaxrs/TestServerInfoObject.java
> +            assertEquals("123", node.get("clusterNodeId").asText());
Can you assert `clusterEnabled` too?

2020-12-07 13:00 UTC, efge approved these changes

2020-12-07 14:59 UTC, troger approved these changes

2020-12-08 08:53 UTC, merged