Feat nxp 29932 stream introspection
nuxeo/nuxeo pull request #4518
Opened 2020-12-07 08:47 UTC by bdelbosc

2020-12-07 08:47 UTC, nuxeojenkins commented
View issues in JIRA:
- [NXP-29934](https://jira.nuxeo.com/browse/NXP-29934): Report Stream Processors topologies on node start
- [NXP-29933](https://jira.nuxeo.com/browse/NXP-29933): Create a MetricsReporter dedicated for Stream introspection
- [NXP-29935](https://jira.nuxeo.com/browse/NXP-29935): Create a Stream processor introspector
- [NXP-29940](https://jira.nuxeo.com/browse/NXP-29940): Add a management endpoint for Stream introspection

2020-12-09 11:21 UTC, kevinleturc reviewed
Grat work 💪

2020-12-09 11:21 UTC, kevinleturc commented on modules/runtime/nuxeo-runtime-stream/src/main/java/org/nuxeo/runtime/stream/StreamMetricsReporter.java
> +            }
Is the comment still relevant?

2020-12-09 13:00 UTC, efge requested changes

2020-12-09 14:01 UTC, bdelbosc commented on modules/core/nuxeo-core-bulk/src/main/java/org/nuxeo/ecm/core/bulk/introspection/StreamIntrospectionComputation.java
> +    }
yes probably but this is only the early stage of the representation that can be refactored depending on how we want to exploit it, the important thing is to start publishing the information (metrics and processor producer code)

2020-12-09 17:08 UTC, bdelbosc commented
PR screwed up, review taken in account in https://github.com/nuxeo/nuxeo/pull/4534

2020-12-09 17:08 UTC, closed without merging