NXP-29969 component manager listener
nuxeo/nuxeo pull request #4544
Opened 2020-12-14 14:11 UTC by atchertchian

2020-12-14 14:11 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29969](https://jira.nuxeo.com/browse/NXP-29969): Improve registration of ComponentManager listeners

2020-12-22 11:18 UTC, efge submitted a review, later dismissed

2020-12-22 11:18 UTC, efge commented on modules/runtime/nuxeo-runtime-test/src/test/java/org/nuxeo/runtime/MockEventsInfo.java
> +    public int beforeStop = 0;
Old code but `= 0` is redundant. You should probably keep Bogdan's name in the contributors as well.

2020-12-22 11:18 UTC, efge commented on modules/runtime/nuxeo-runtime-stream/src/main/java/org/nuxeo/runtime/stream/StreamServiceImpl.java
> +        log.debug("afterStart");
Maybe change the debug messages?

2020-12-22 12:35 UTC, kevinleturc approved these changes

2020-12-22 13:03 UTC, atchertchian commented
TODO: check regression visible on StreamWorkManager tests

2020-12-22 13:15 UTC, atchertchian commented
Reverting migration of WorkManagerImpl and StreamWorkManager listeners: there are intricate initializations impacted, listeners can stay as is.

2020-12-22 16:36 UTC, atchertchian commented
Need to refine the behavior: some listeners were previously registered at component start, so listener start methods were following the start order on components (which is not the case anymore, visible in unit tests were UserProfile service expects the RepositoryService to have initialized the repo)

2020-12-23 10:03 UTC, efge commented on modules/runtime/nuxeo-runtime/src/main/java/org/nuxeo/runtime/model/impl/ComponentManagerImpl.java
>          public void beforeStop(boolean isStandby) {
To be consistent I think that stop should use the reverse order.

2020-12-23 10:04 UTC, efge requested changes

2020-12-23 10:04 UTC, efge commented on modules/runtime/nuxeo-runtime/src/main/java/org/nuxeo/runtime/model/impl/ComponentManagerImpl.java
> +            sortedForStart().forEach(listener -> listener.afterRuntimeStart(ComponentManagerImpl.this, isResume));
To be consistent I think that stop should use the reverse order.

2020-12-23 10:16 UTC, efge approved these changes

2020-12-23 13:46 UTC, efge submitted a review, later dismissed

2021-01-08 08:21 UTC, atchertchian commented
Will rebase on master (trying to understand what can cause validation issues)

2021-01-08 15:52 UTC, atchertchian commented
Ftests are actually failing because of ERROR log

`[org.nuxeo.ecm.user.center.profile.UserProfileImporter] No importer configuration could be found`

2021-01-08 17:04 UTC, atchertchian commented
Fixed change to UserProfileServiceImpl (should not schedule import if config is null)

2021-01-11 14:25 UTC, efge approved these changes

2021-01-12 08:40 UTC, merged