NXP-29991: Add configuration flag
nuxeo/nuxeo pull request #4558
Opened 2020-12-24 15:57 UTC by kevinleturc

2020-12-24 15:57 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29991](https://jira.nuxeo.com/browse/NXP-29991)

2020-12-24 16:03 UTC, efge approved these changes

2020-12-24 16:06 UTC, ataillefer approved these changes

2021-01-04 09:48 UTC, troger approved these changes

2021-01-12 09:34 UTC, troger submitted a review, later dismissed

2021-01-12 10:11 UTC, efge requested changes

2021-01-12 10:11 UTC, efge commented on modules/platform/nuxeo-preview-core/src/main/java/org/nuxeo/ecm/platform/preview/adapter/ZipPreviewer.java
> +            }
```
List<Blob> blobs = result.getBlobs();
if (Framework.getService(ConfigurationService.class).isBooleanTrue(SANITIZE_ZIP_PREVIEW)) {
    blobs.replaceAll(this::sanitize);
}
return blobs;
```

2021-01-13 06:04 UTC, ataillefer approved these changes

2021-01-13 16:38 UTC, efge approved these changes

2021-01-13 16:39 UTC, merged