NXP-29966: compute video info, previews, storyboard and conversions only when needed
nuxeo/nuxeo pull request #4583
Opened 2021-01-11 16:03 UTC by troger

When creating a document (new document or version), we compute:
- the video info only if the width and height is set to 0
- the video previews only if empty
- the video storyboard only if empty
- only the missing automatic conversions not present on the document

When updating the main blob document, everything is reset and recomputed.

2021-01-11 16:04 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29966](https://jira.nuxeo.com/browse/NXP-29966): Fix recomputation processes when creating a version for documents with 'Video' facet

2021-01-11 16:19 UTC, efge requested changes

2021-01-11 16:19 UTC, efge commented on modules/platform/nuxeo-platform-video/src/main/java/org/nuxeo/ecm/platform/video/service/VideoServiceImpl.java
> +        launchAutomaticConversions(doc, false);
Could you put this in the interface as a default method instead?

2021-01-11 16:19 UTC, efge commented on modules/platform/nuxeo-platform-video/src/main/java/org/nuxeo/ecm/platform/video/service/VideoStoryboardWork.java
> +        save = updatePreviews(doc, video) || save;
`save |= updatePreviews(doc, video);`

2021-01-11 17:15 UTC, efge approved these changes

2021-01-12 09:23 UTC, kevinleturc submitted a review, later dismissed

2021-01-12 14:28 UTC, ataillefer approved these changes

2021-01-12 14:28 UTC, ataillefer commented on modules/platform/nuxeo-platform-video/src/test/java/org/nuxeo/ecm/platform/video/extension/TestVideoImporterAndListeners.java
> +        // only video info and previews computed
```suggestion
        // only video info and previews are set
```
as they actually haven't been computed by the listener

2021-01-12 14:34 UTC, troger commented
Updated following @ataillefer's comment.

2021-01-12 14:39 UTC, kevinleturc approved these changes

2021-01-12 14:46 UTC, efge approved these changes

2021-01-12 14:50 UTC, ataillefer approved these changes

2021-01-14 10:13 UTC, merged