NXP-29872: Better handle requested URL parameter
nuxeo/nuxeo pull request #4803
Opened 2021-05-26 21:22 UTC by ataillefer

2021-05-26 21:22 UTC, nuxeojenkins commented
View issue in JIRA: [NXP-29872](https://jira.nuxeo.com/browse/NXP-29872)

2021-05-27 06:55 UTC, kevinleturc approved these changes

2021-05-27 12:55 UTC, efge requested changes

2021-05-27 12:55 UTC, efge commented on modules/platform/nuxeo-platform-web-common/src/main/java/org/nuxeo/ecm/platform/ui/web/auth/NuxeoAuthenticationFilter.java
> +            // malformed URI, the requested URL is not absolute
If the URL cannot be parsed I'd be conservative and throw `new NuxeoException(SC_BAD_REQUEST)` too.

2021-05-27 13:04 UTC, efge approved these changes

2021-05-27 13:12 UTC, kevinleturc approved these changes

2021-06-01 19:29 UTC, ataillefer commented
Rebased on master to benefit from the broken build fix, see https://github.com/nuxeo/nuxeo/commit/6bc0ea6e531d4cb0cc643e9fee0f8c02d0ebe4dc and [NXP-30449](https://jira.nuxeo.com/browse/NXP-30449).

2021-06-02 09:02 UTC, kevinleturc submitted a review, later dismissed

2021-06-02 13:15 UTC, efge submitted a review, later dismissed

2021-06-07 08:14 UTC, kevinleturc approved these changes

2021-06-08 09:07 UTC, merged